### ISSUE TITLE
ActionDropdown buttonProps

### ISSUE THREAD

**Issue by AlanLoovees** [bigbinary/neeto-ui#1045]
[Loom video about the issue](https://www.loom.com/share/282bb28cb4ae4facbeabf39d9480cb12)

@yedhink

**Comment by yedhink** [comment]
@amaldinesh7 _a Can you please take a look into this? Thanks.

**Comment by amaldinesh7** [comment]
@AlanLoovees I think the implementation of ActionDropdown needs a proper revamp, thus I am not adding any particular fix for this issue. One workaround for this issue is you can override the buttonProps of the dropdown trigger by
`dropdownProps={{buttonProps:{type:"button"}}}`.

But this will override other properties as well, in that case, you can specify the properties that you need for the dropdown button. for eg `size`.

**Comment by amaldinesh7** [comment]
@AlanLoovees We have separated out `buttonProps` and `dropdownProps`. There shouldn't be any conflict happening now.
