### ISSUE TITLE
New history is pushed on navigating back - BlockNavigation

### ISSUE THREAD

**Issue by abhishekt98** [bigbinary/neeto-ui#1154]
Video : https://vimeo.com/715895274/f5b424c3f4

 Please check the below code for reference which handle the issue mentioned.
```
import React, { useState, useEffect, useRef } from "react";

import { Alert } from "neetoui";
import { useTranslation } from "react-i18next";
import { useHistory } from "react-router-dom";

const PageNavigateAlert = ({ when }) => {
  const { t } = useTranslation();
  const history = useHistory();

  const [showPrompt, setShowPrompt] = useState(false);
  const unblockRef = useRef();

  const handleUnblock = () => {
    if (showPrompt) {
      setShowPrompt(false);
      unblockRef.current?.();
    }
  };

  useEffect(() => {
    const unblock = history.block((transition, action) => {
      if (when) {
        setShowPrompt(true);
        unblockRef.current = () => {
          unblock();
          switch (action) {
            case "PUSH":
              history.push(transition);
              break;
            case "REPLACE":
              history.replace(transition);
              break;
            case "POP":
              history.goBack();
              break;
          }
        };
        return false;
      }

      return undefined;
    });

    return () => {
      unblock();
    };
  }, [when]);

  return (
    <div>
      <Alert
        title={t("common.pageNavigate.title")}
        message={t("common.pageNavigate.description")}
        isOpen={showPrompt}
        onClose={() => setShowPrompt(false)}
        onSubmit={handleUnblock}
      />
    </div>
  );
};

export default PageNavigateAlert;

```
cc: @labeebklatif

**Comment by amaldinesh7** [comment]
@ajil-paul _a Please take a look at this issue and let me know what is a viable solution.

**Comment by ajil-paul** [comment]
@amaldinesh7  The issue is from the library we are using for block navigation. Even if we try to fix the problem as @abhishekt98 mentioned in the video, there will be the same issue while clicking the forward navigation button. The problem is the action parameter that we are getting from history (instance of useHistory) is not correct in the case of forwarding navigation. There is only three actions (PUSH, REPLACE, POP). When the user click on Forward nav button, we are getting the action as POP. So I am not able to know whether the user clicked on the forward nav button. If we ignore the case of Forward nav button, then I think we can move on with the referred code by @abhishekt98

**Comment by amaldinesh7** [comment]
I think we can make this tradeoff as users will be relying more on backward nav rather than forward nav. Please make the required changes @ajil-paul _a
