### ISSUE TITLE
Question regarding use of MenuItem in `Dropdown` component.

### ISSUE THREAD

**Issue by ravijyoti3** [bigbinary/neeto-ui#1327]
![Components - Dropdown - Default ⋅ Storybook 2022-09-21 01-04-30](https://user-images.githubusercontent.com/44156359/191451626-ddc16438-2875-4b41-a3bb-8b8dcc5e0931.png)

Why we have used the `MenuItem.Button` over a simple `li`? As I tried using `li` and `MenuItem.Button`, **but the UI didn't undergo any notable changes.**

Reference: https://neetoui.onrender.com/?path=/docs/components-dropdown--default

**Comment by karthiknmenon** [comment]
@praveen-murali-ind  _a

**Comment by yedhink** [comment]
I believe it might be because we can pass in the styling options for the MenuItem button, like `style="danger"` etc. But if this is the case, then we need to document the same and advocate to use a best practice, Meaning when to prefer `li` as dropdown item and when to prefer `MenuItem.Button`. Show valid examples.

**Comment by praveen-murali-ind** [comment]
@yedhink @ravijyoti3 Please watch this loom video for more details.

https://www.loom.com/share/985ac83d1f8a4cd0bd687c5c67800e58

https://neeto-engineering.neetokb.com/articles/accessibility

**Comment by ravijyoti3** [comment]
Thank you, Praveen for the insights.

**Comment by yedhink** [comment]
Thanks Praveen for the explanation. I think we can close this issue.
