### ISSUE TITLE
Product description in App Switcher

### ISSUE THREAD

**Issue by Amaljith-K** [bigbinary/neeto-ui#1330]
Explanation: https://vimeo.com/752476869/16c0cd4ab6

The engineering work needs to be done on neetoui.
@neerajdotname what do you think is the best way to get a catchy description for each project?
Should I ask the corresponding project managers?

**Comment by neerajdotname** [comment]
@Amaljith-K Let's take this up a few months later. That's because I'm not for whom to optimize it for. For the folks who know which product does what all the description will just take up extra space and the place becomes noisy. I feel like we would redesign the app switcher and rather than have a columnar style we will explore other style where most frequently used products are at the top and rest at the bottom with desc etc. But all this is for later.
