### ISSUE TITLE
Questions/suggestions regarding `EmailInput` component docs

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#1345]
https://www.loom.com/share/8bad9655eab143189ff43c87be5c1217

**Comment by yedhink** [comment]
@amaldinesh7 _a Please take a look into this.

cc: @praveen-murali-ind

**Comment by amaldinesh7** [comment]
@sreerag-ms _a

**Comment by sreerag-ms** [comment]
@amaldinesh7  Email Input accepts multiple emails by default. It doesn't make sense to add email Input with a single option as it can be easily achieved using `Input`. `EmailInput` is just a special case of `input`/`select` that is heavily reused across neeto. 
IMO name of the component is the issue here. Something like `MultiEmailInput` or `EmailListInput` should avoid confusion.
Lmk your thoughts.

**Comment by karthiknmenon** [comment]
@deepakjosp _a Please follow up on this thread and let us know if you have any confusions regarding this.
