### ISSUE TITLE
Remove Link component

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#139]
Parent issue: https://github.com/bigbinary/neeto-help-web/issues/9114

@goutham-subramanyam

So what should be done at the places in neeto-help where `Link` component is used? What should we replace it with?

cc: @edwinbbu

**Comment by edwinbbu** [comment]
@yedhink 
**Button** component supports all the features of the Link component
eg `<Button style="link" to="url"/>`
If we pass `to` prop to button, it will act as link

**Comment by yedhink** [comment]
@edwinbbu 
So just to confirm once again, at all places where `Link` component is used, I can replace with `<Button to={url}` component, correct?

**Comment by edwinbbu** [comment]
Yes please not that in the parent issue. The Link component was imported from NitroUI. 
Link can also be imported from "react-router-dom" - `import { Link } from "react-router-dom";`
You'll see that in many places of neetohelp application. 
Button component in neetoui is internally using Link component from "react-router-dom".

Link can be directly used which is not wrong since its from "react-router-dom". There might be specific cases were we want to the button to act as link. For that we are supporting link in button component.
