### ISSUE TITLE
Animations run incorrectly on element with autofocus input

### ISSUE THREAD

**Issue by sandip-mane** [bigbinary/neeto-ui#1396]
Ref: https://github.com/bigbinary/neeto-planner-web/issues/2665

**Comment by karthiknmenon** [comment]
@praveen-murali-ind _a

**Comment by praveen-murali-ind** [comment]
This issue appears to be due to a bug in WebKit (the engine that powers Safari) where autofocus causes animations to be run incorrectly. 

https://bugs.webkit.org/show_bug.cgi?id=219506

@karthiknmenon _a Could you please check whether we can autofocus the Input once the CSS transition is completed.

**Comment by akkshaylawrence** [comment]
@praveen-murali-ind I have updated this ticket's estimate for the following reasons.

- The issue had some minor blockers for testing in the product due to some issue with `yalc`.
- Even though the issue with autofocus in form fields was fixed, there seems to be some other issue that caused the animation issues when I tested in neetoPlanner, which needs to be addressed.

**Comment by sumanranjanpanda** [comment]
@akkshaylawrence Any updates as we started working on it 2 weeks ago?

**Comment by akkshaylawrence** [comment]
@sumanranjanpanda The PR is actually raised and @amaldinesh7 has reviewed it, but he suggested a call with @praveen-murali-ind before merging it, that is why this is still open, We will get this merged once that happens.

**Comment by sumanranjanpanda** [comment]
@akkshaylawrence  Okay, let's do that fast. We should not keep open PRs like that.
