### ISSUE TITLE
Should we add className prop to `Form` component?

### ISSUE THREAD

**Issue by AbhayVAshokan** [bigbinary/neeto-ui#1411]
It would be more natural and readable to provide a className prop to the new Form component as 
```jsx
<Form className="...">{children}</Form>
```

Instead of 
```jsx
<Form formProps={{ className: "...." }}>{children}</Form>
```

Please share your thoughts @karthiknmenon 

A similar argument can be also provided for `initialValues`, `validationSchema` and mandatory formik props.

**Comment by karthiknmenon** [comment]
I guess we can move `className` out as props. However, the rest I would still like to keep them as `formikProps` and `formProps` as the list would be never ending. And since `Form` component wraps both `Form` and `Formik` components into a single wrapper component, passing in props like `initialValues`, `validationSchema` does not feel right.

cc: @amaldinesh7 @ajmaln

**Comment by karthiknmenon** [comment]
@karthiknmenon _a

**Comment by AbhayVAshokan** [comment]
@karthiknmenon iirc we use a state (say `hasSubmitted`) in every form to trigger validations only after the first submission using `validateOnBlur` and `validateOnChange` props. Should we bring this behavior within the `Form` component?
