### ISSUE TITLE
Fix Storybook caching issue

### ISSUE THREAD

**Issue by josephmathew900** [bigbinary/neeto-ui#1699]
Ref: https://github.com/bigbinary/neeto-deploy-web/issues/1155

cc: @Amaljith-K

**Comment by josephmathew900** [comment]
@amaldinesh7 _a

**Comment by josephmathew900** [comment]
@Calvinwilson99 _a Assigning this issue to you since you have already worked on issue https://github.com/bigbinary/neeto-molecules/issues/192.

**Comment by Calvinwilson99** [comment]
https://www.loom.com/share/b4985012f6d74216b9f1083844edf169
This video summarizes my work of the last 2 days. It took longer than expected to try all the different approaches as the expected solution did not work in neetoUI. The URL's were still getting cached.
The next things to try is moving from http-server to express so that I can write a middleware that intercepts requests and adds the hash.
I would need a total time of 3D to finish moving to express.
cc: @josephmathew900
