### ISSUE TITLE
Our dependencies are too outdated or obsolete

### ISSUE THREAD

**Issue by Amaljith-K** [bigbinary/neeto-ui#1789]
- We are using framer-motion version 4.1.17. It is a 2.5 year old release. The latest available version is 10.16.1. We need to migrate as soon as possible.
- tippyjs is no longer being maintained. The version we are using is 2.5 years old. Its last release was on Oct 29, 2021. We need to find alternatives.
- We don't need react-hotkeys-hook. We have a more robust implementation of useHotkeys hook in neeto-commons-frontend/react-utils. We can either move it to a separate package/bundle instead of using the whole neeto-commons-frontend/react-utils in neetoui.

There might be more such dependencies. Please look into all of them.

Reference: [Memory issue while editing test cases](https://neeto-engineering.neetoplanner.com/NT/board/236?commentId=e4c66ac2-3838-49b8-9c11-e28fbc16638c)

@amaldinesh7 _a
cc @ajmaln -a

**Comment by AbhayVAshokan** [comment]
> We don't need react-hotkeys-hook. We have a more robust implementation of useHotkeys hook in neeto-commons-frontend/react-utils.

As a side note, no neetocommons hooks are used in neetoUI. The `@bigbinary/neeto-commons-frontend` package is installed only for the configuration files (ESlint, Prettier, Babel, and Webpack resolve). This ensures that `@bigbinary/neeto-commons-frontend` (and it's peer dependencies) are not a requirement for using neetoUI.

**Comment by Amaljith-K** [comment]
@AbhayVAshokan _a I forgot that for a moment. I have updated the description taking that into account.

**Comment by Amaljith-K** [comment]
Removing the priority badge because it is not blocking anything.

**Comment by ajmaln** [comment]
@CalvinChiramal _a

**Comment by Amaljith-K** [comment]
@adityamahajan-io _a please take this up

**Comment by Amaljith-K** [comment]
@CalvinChiramal _a please take this up

**Comment by CalvinChiramal** [comment]
@ajmaln _a. @Amaljith-K Please let me know your thoughts.

Tailwind upgrade:
- `npm:@tailwindcss/postcss7-compat`: We are still using a 2 year old version of tailwind so that we could keep it compatible with `postcss` v7. We have already upgraded `postcss` to v8, so now we can upgrade tailwind to the latest version. This should in fact be done in most of our packages and web apps as well. Storybook still uses `postcss` v7 while bundling with the `@storybook/addon-postcss` package. This could potentially introduce breaking changes as tailwind has changed some of the classnames it uses. Eg: `break-word` has been changed to `break-words`, colours like `gray` have been replaced with `slate`.
- `@storybook/addon-postcss`: Currently depreciated. Use `@storybook/addon-styling-webpack`. This will also upgrade postcss to use v8 in storybook and tailwindcss can be upgraded.
- `autoprefixer`: Upgrade to latest version(currently 9.0.0). No breaking changes introduced. All other packages and products use 10.x.x. Upgrade along with tailwind.

Unused packages:
- `file-loader`, `html-loader`, `html-webpack-plugin`: This was used along with webpack config. We are now using rollup as well as file-loader is depreciated. I have removed these packages in the linked PR. In fact, these can be removed from all our web apps as well since we are not using this in our webpack config(Checked in `neeto-commons-frontend`).
- `react-spring`, `react-outside-click-handler`, `react-test-renderer`: Unused and can be removed safely. Removed in linked PR.
- `chromatic`: This was being used to run the jest tests as a CI check and deploy review app of the storybook. This is currently not working in any of the PR’s. We can remove chromatic and use neetoDeploy+neetoCI similar to how `neeto-molecules` is handling it.

Packages to upgrade:
- `react-linkify`: We are using a version that was released 4 years ago and it does not seem to be maintained anymore. I found one alternative `linkify-react` that works almost the same way but its github repo is not public and there is very little documentation. I also don't think this is something we need to upgrade since its working is fairly straightforward.
- `framer-motion`: There was only a single breaking change for this so I have upgraded it and verified that it works fine in the linked PR.
- `tippyjs`: `floating-ui` is currently the best replacements for `tippyjs`. Had a cursory look at `floating-ui` and the implementation is going to be very different than how we are using `tippy-js`. `tippy-js` handled hover, click and other cases internally and allowed us to control it with the help of props. `floating-ui` on the other hand exposes hooks for each of these actions that we can attach to the component. Will build a POC to check this.
- `react-hotkeys-hook`: Remove and use `useHotKeys` from `neeto-commons-frontend`. There is only a single usage of this hook. If possible, the simplest option is copying the `useHotKeys` hook implementation from `neeto-commons-frontend` into neetoUI. Else, we can add it to `neeto-cist` since it’s a public repository and can be used in neetoUI.

**Comment by Amaljith-K** [comment]
Here are my comments on package upgrades:
- The entire neeto ecosystem should upgrade to new tailwindcss altogether. Let's skip it for now.
- `neeto-cist` can't contain react utilities. neeto-cist is designed in such a way that it should function in a platform/framework independent fashion. If we add react hotkeys utilities, we are binding it to browser context and react library, which goes against its vision and scope. Instead, we can create a new package, which solely contains the hotkeys hook. We built the hook on our own since there weren't any good open-source packages to meet our needs. If we move that code to a separate package and open-source it, it will also indirectly act as marketing material.

**Comment by Amaljith-K** [comment]
@CalvinChiramal _a can you create issues based on the action items required?
Tag me in those issues. I'll assign them to the right person.

**Comment by CalvinChiramal** [comment]
@Amaljith-K _a. I have created issues and added them in the description. Should we reopen this issue as an epic to track them?

**Comment by Amaljith-K** [comment]
No. We can approach each issues individually.
