### ISSUE TITLE
Cancel button from ActionBlock isn't working in some scenarios

### ISSUE THREAD

**Issue by abilash-sajeev** [bigbinary/neeto-ui#1810]
Ref: https://github.com/bigbinary/neeto-desk-web/issues/17361

https://github.com/bigbinary/neeto-ui/assets/35305344/9c2d7b11-29a2-45e7-8a3d-c837db0aa702

**Comment by adityamahajan-io** [comment]
@ajmaln Please have a look: https://www.loom.com/share/85b928a7df044e75bc05fc4e8438688c
This is a peculiar issue caused by a layout shift caused due to the order of events: 
When we click the cancel button:
1. The input field is blurred
2. As the input field is blurred, it renders the error message and causes a layout shift.
3. onClick happens after onBlue is completed, so the mouse pointer is no longer on the clickable area due to the layout shift.

We will need to figure out a way to prevent the layout shift. Please let me know your thoughts.

**Comment by sreerag-ms** [comment]
> Please have a look: https://www.loom.com/share/85b928a7df044e75bc05fc4e8438688c

Another approach would be preventing the default behavior on mouseDown events for the cancel button. This will not trigger the validation on clicking cancel.

```
          cancelButtonProps={{
.           ...otherProps,
            onMouseDown: e => e.preventDefault()
          }}
```

**Comment by adityamahajan-io** [comment]
@sreerag-ms That's a good idea. Adding `onMouseDown: e => e.preventDefault()` fixes the problem.
