### ISSUE TITLE
Migrate from `react-linkify` to `linkify-react`

### ISSUE THREAD

**Issue by CalvinChiramal** [bigbinary/neeto-ui#1961]
Look into the implementation of [`linkify-react`](https://linkify.js.org/docs/linkify-react.html). If it satisfies our requirements, migrate to that package. Else, look into building a more robust implementation from our side.
cc: @Amaljith-K

**Comment by ittyjose** [comment]
As per the lib only 3 bugs are currently open and that is not at all related to linky-react [link](https://github.com/Hypercontext/linkifyjs/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to it . What we need to provide is default protocol as `https` always in options.


Package have recent version releases happened on 2 weeks before. 

Instead of `componentDecorator` we have to pass `render` in options.

**Preview of options**

`const options = {
    defaultProtocol: "https",
    rel: "noreferrer",
    target: "_blank",
    render: {
      url: ({ attributes, content }) => <a {...attributes}>{content}</a>,
    },
  };`


In general, this package is a good replacement and have recent activities happening in repo.
