### ISSUE TITLE
Add data-cy for addTag button

### ISSUE THREAD

**Issue by yatharthvij** [bigbinary/neeto-ui#2011]
Current selector: ".neeto-ui-btn neeto-ui-btn--icon-only"
Ref: 
<img width="1440" alt="Screenshot 2023-11-22 at 2 49 39 PM" src="https://github.com/bigbinary/neeto-ui/assets/75108777/3ede44e3-9b97-4574-a164-56f56d6558f3">

**Comment by ajmaln** [comment]
@yatharthvij _a Isn't this the same issue as: https://github.com/bigbinary/neeto-tags-nano/issues/58? The issue was transferred to neeto-tags-nano as it needs to be handled from neeto-tags, not neetoUI

There is a PR currently assigned to you for review for the same: https://github.com/bigbinary/neeto-tags-nano/pull/59

**Comment by yatharthvij** [comment]
Duplicate issue for https://github.com/bigbinary/neeto-tags-nano/issues/58
