### ISSUE TITLE
Additional features to the table

### ISSUE THREAD

**Issue by neerajsingh0101** [bigbinary/neeto-ui#2048]
https://www.loom.com/share/c8dbdd0cf2d642e38296261e4aaf8710

@akkshaylawrence _a Please have a call with @praveen-murali-ind before starting the work.

**Comment by akkshaylawrence** [comment]
@neerajsingh0101 The column hide feature is already being implemented in https://github.com/bigbinary/neeto-engineering-ui-ux/issues/224.

Support for **adding columns to the left/right** and the **ability to delete** needs to be added to `neeto-ui` and `neeto-fields-nano` first before implementing it in the products.

I will create a global issue when the above step is done and the requirements for these 2 features are clear.

CC: @praveen-murali-ind @anil-anand @ajmaln

**Comment by akkshaylawrence** [comment]
@praveen-murali-ind Updating the ETA to 2 days to fix the additional issues that were discovered during implementation.

**Comment by akkshaylawrence** [comment]
@neerajsingh0101 @praveen-murali-ind I have recorded a small demo for the features please LMK your thoughts.
https://www.loom.com/share/df2f9702bdd2485a84d39eaa7d214126?sid=b7cdbbb5-773b-4810-971b-f2cad2e30aaf

**Comment by praveen-murali-ind** [comment]
@akkshaylawrence The POC looks good. But the `Insert column left`,  `Insert column right` and `Delete column` functionalities are not relevant to `Contacts` table. As per my understanding, the neetoForm submissions table needs these features.

<img width="913" alt="Screenshot 2023-12-22 at 10 58 40 AM" src="https://github.com/bigbinary/neeto-ui/assets/48869249/0879b8d5-7498-44ff-8b61-3f6943a7b1c3">

---

Let’s remove the danger style from `Delete column` since we are already using an Alert component on click.

<img width="265" alt="Screenshot 2023-12-22 at 11 00 20 AM" src="https://github.com/bigbinary/neeto-ui/assets/48869249/5d736b9a-75d7-41aa-b566-3fa882ff7045">
<img width="466" alt="Screenshot 2023-12-22 at 11 00 29 AM" src="https://github.com/bigbinary/neeto-ui/assets/48869249/b22a3494-0d50-4447-a4ed-9533a7b89eac">

**Comment by akkshaylawrence** [comment]
@praveen-murali-ind Understood, I choose neetoChat because the hide column functionality which I was dependent on was already merged there. I will start implementation of the above features there when that feature is merged in neetoForm.

**Comment by neerajsingh0101** [comment]
@praveen-murali-ind @akkshaylawrence https://www.loom.com/share/f927a65a729347a5b785a57b62bab664

**Comment by akkshaylawrence** [comment]
@neerajsingh0101 The support for the above features have been rolled out in the table component of the latest version of neetoUI.

As far an rolling out of the features to the products is concerned, I'd suggest we do it on an _as-needed_ basis since most of the tables in the products don't need these features implemented from the get go and it should be up to the product team to decide based on the requirement.

neetoForm submissions table like you pointed out, is a case were it makes sense to add these features so I will create a ticket and implement it there. 

LMK your thoughts on this approach.

CC: @praveen-murali-ind

**Comment by neerajsingh0101** [comment]
@akkshaylawrence sounds good. 👍
