### ISSUE TITLE
Allow showing timezone next to the date in datepicker

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#2149]
@farhanlatheef _a https://yedhin.neetorecord.com/watch/5d9ef276-c52d-4daa-992f-1eba760190e1

Please note: The tooltip is not a solution. One may not hover on top of the due date but rather be quick jump into confusion by seeing the dates. So it's better to always show the timezone next to the date.

cc: @josephmathew900 @praveen-murali-ind @lakshyakanungo

**Comment by yedhink** [comment]
@farhanlatheef _a That definitely would work. But the thing is, for all neeto products where we are using date-picker, I feel we should be showing the timezone next to the date. 

There's already an issue to standardize timezone usage https://github.com/bigbinary/neeto-engineering-web/issues/689. So either browser timezone or neetoAuth timezone will get used. 

The idea behind adding this timezone suffix is to bring clarity to the end user in what timezone they are seeing the date.

So this is my suggestion:
- Have a default icon/tag to display timezone based on the neetoAuth profile timezone. If user has passed in a custom timezone via the `timeZone` prop, then override default one and show it in the icon/tag.
- This icon can be display if a prop like say `showTimezone` is passed to our DatePicker.

Lemme know your thoughts.

**Comment by josephmathew900** [comment]
@yedhink https://joseph-mathew.neetorecord.com/watch/8c38ba30-fb85-477e-9e99-2018e9a5709d

**Comment by yedhink** [comment]
@josephmathew900 Mentioning in help doc won't work. Because not everyone remembers everything mentioned in help doc. A person might read a help doc when they start out with the product, but after a while, let's 6 months into it, they might forget minor details. But I agree with your point that showing timezone everywhere is unnecessary.

> do we need to show timezone everywhere datetime/time picker is used?

No. Let the host app decide if they need to show it in certain pages. In neetoPlanner when it comes to `due date` field, it's essential to show timezone. So a prop like `showTimezone` should do the job.

**Comment by josephmathew900** [comment]
@yedhink We can take up this issue once the UI of DatePicker and TimePicker components is finalized in this [issue](https://github.com/bigbinary/neeto-engineering-web/issues/630). @AbhayVAshokan is working on that. 

But as you mentioned in [this comment](https://github.com/bigbinary/neeto-ui/issues/2149#issuecomment-2026751085), we cannot add a logic to display timezone by default from the neetoAuth profile timezone because this is a component library and we cannot integrate neeto specific logic into this. What we can do is to have a timezone prop, and if the product decides to show the timezone they can pass it from the product.

cc: @praveen-murali-ind @farhanlatheef

**Comment by josephmathew900** [comment]
We will take up this issue after completing https://github.com/bigbinary/neeto-ui/issues/2234.

**Comment by josephmathew900** [comment]
@gaagul _a

**Comment by gaagul** [comment]
Fixed by: https://github.com/bigbinary/neeto-ui/pull/2239
