### ISSUE TITLE
Consistency in DatePicker component

### ISSUE THREAD

**Issue by chiraggshah** [bigbinary/neeto-ui#2248]
https://chirag-shah.neetorecord.com/recordings/905a4381-63e3-4fdb-8661-5c630e90394f

**Comment by deepakjosp** [comment]
@chiraggshah this is the current behaviour of the date and time picker in antd. I checked the documentation and didn't find anything to configure the behaviour. This needs to be fixed in the antd library, I've created a ticket for the same over there.

Ref: https://github.com/ant-design/ant-design/issues/50288

cc: @josephmathew900

**Comment by chiraggshah** [comment]
@deepakjosp : Looks like the issue was fixed in antd. Should we create a separate issue to bump up antd?

**Comment by deepakjosp** [comment]
@chiraggshah I've created an issue and added to the upcoming milestone.

https://github.com/bigbinary/neeto-ui/issues/2281
