### ISSUE TITLE
Icon and text in tabs should act as link 

### ISSUE THREAD

**Issue by edwinbbu** [bigbinary/neeto-ui#278]
Ref https://github.com/bigbinary/aceinvoice-web/issues/7598

cc @goutham-subramanyam, @dineshpanda

**Comment by goutham-subramanyam** [comment]
<img width="685" alt="Screenshot 2021-05-21 at 3 43 00 AM" src="https://user-images.githubusercontent.com/24496302/119055556-e45f4e80-b9e6-11eb-91cf-b6dabf364466.png">

@edwinbbu The issue is not happening in neetoui. It is happening due to bad code in aceinvoice. Please check the code before creating issues in neetoui.
