### ISSUE TITLE
Add data-cy attribute to the elements

### ISSUE THREAD

**Issue by sagar18041** [bigbinary/neeto-ui#58]
https://www.loom.com/share/5d55b39d84dc4ef7a01ef70a69de4307

We need to add an attribute as `data-cy` to the HTML elements. The prop name would be `dataCy`.
This would be used by Cypress to uniquely identify the elements that would be used in Automation testing.

**Comment by edwinbbu** [comment]
@sagar18041 Yes all neeto-ui elements should support `data-cy` or any other testing ids. Hence all the components should have something called `{...otherProps}`. OtherProps will capture any extra prop to the component.
The prop name to be passed will be `data-cy` instead of `dataCy`.

The otherProps is missing for the label component which will be added. 

cc @vinay0x , @yedhink , @goutham-subramanyam
