### ISSUE TITLE
Verify tree shaking is done properly with popper 

### ISSUE THREAD

**Issue by edwinbbu** [bigbinary/neeto-ui#630]
Ref: https://popper.js.org/docs/v2/performance/

@amaldinesh7 _a

performance _t

**Comment by edwinbbu** [comment]
@ajmaln _a Can you check this out.

**Comment by ajmaln** [comment]
@edwinbbu as per https://popper.js.org/docs/v2/performance/, to implement treeshaking, the import should be like below:

```js
import { createPopper } from '@popperjs/core/lib/popper-lite';
```

Since we are using `usePopper` hook from `react-popper`, the import for `createPopper` is not following the treeshaking approach on the library. Ref: https://github.com/popperjs/react-popper/blob/master/src/usePopper.js#L4.

Also there is an open [issue](https://github.com/popperjs/react-popper/issues/380) for enabling tree shaking in `react-popper`.

cc: @amaldinesh7

**Comment by karthiknmenon** [comment]
@AJIL-PAUL _a could you please check?

cc: @ajmaln, @amaldinesh7

**Comment by AJIL-PAUL** [comment]
We are using ` react-popper`  for `usePopper`  hook. The `react-popper` is importing the `@popperjs/core` module of `Popper(19.3k)`
For tree shaking, they should use `@popperjs/core/lib/popper-lite`  module.
In the [issue](https://github.com/popperjs/react-popper/issues/380) about enabling tree shaking, they said they can't import `@popperjs/core/lib/popper-lite`  module in ` react-popper`

**Comment by amaldinesh7** [comment]
Closing the issue for now, since the react-popper doesn't support tree shaking as of now.
