### ISSUE TITLE
Remove checkmark from buttons

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/neeto-ui#702]
https://www.loom.com/share/61b847a219e648898ad5d5c37701164e

**Comment by amaldinesh7** [comment]
NeetoUI buttons do not have a checkmark by default. We have the option to set an icon to the left or right of the text in a button. This is can be fixed by removing the icon prop from the button at the project level.

<img width="1142" alt="Screenshot 2021-12-09 at 5 48 23 PM" src="https://user-images.githubusercontent.com/33386004/145395072-9b92ad11-fc31-45a2-9180-f02b9e358a1b.png">
This is the default button.

**Comment by amaldinesh7** [comment]
One of the Formik components had it by default, will get it removed.
