### ISSUE TITLE
Fix delay while opening Modal

### ISSUE THREAD

**Issue by praveen-murali-ind** [bigbinary/neeto-ui#772]
@praveen-murali-ind
The customer creation modal is having a noticeable amount of frame drop. Is it fixable?

https://user-images.githubusercontent.com/85148587/150116679-0fbd3524-2d44-4323-b35b-3cdb1a0d98c5.mov

_Originally posted by @Amaljith-K in https://github.com/bigbinary/neeto-chat-web/issues/2089#issuecomment-1016328480_

**Comment by praveen-murali-ind** [comment]
@ajmaln _a Could you please check this issue.

**Comment by karthiknmenon** [comment]
@AJIL-PAUL _a Please take a look.

**Comment by AJIL-PAUL** [comment]
@karthiknmenon 
We are using same animation duration for both `Pane` and `Modal` ( `300 ms` ). 

I think, [here](https://github.com/bigbinary/neeto-chat-web/pull/2089#issuecomment-1016328480) this issue happened because we are creating a Modal on top of a Pane. I have tested it. There is some lag if we are showing a Modal on top of another one or a Pane.  And I think it's a performance issue of [Framer motion](https://www.framer.com/motion/) library

In issue [#442](https://github.com/bigbinary/neeto-replay-web/issues/442), I think it happen because of the `Table`.
During the Modal open, the `Table` is also rendering in the background. The `Table` is heavy during initial rendering. Here, whenever the `Modal` opens, there is a reloading happening to the `Table` in the background. May be thats why the lag. But I didn't understand why the lag during closing.

If required, we can reduce the duration time. May be it can solve the problem to an extend. But I am not sure it will provide a smoothy animation then also. I didn’t  get an alternate solution for this.

**Comment by karthiknmenon** [comment]
@karthiknmenon _a

**Comment by amaldinesh7** [comment]
@Nuzair46 _a

**Comment by Nuzair46** [comment]
@amaldinesh7 https://www.loom.com/share/8528bef062e242dc81db4ebc6c12e6b0
A thing to note is that even in the storybook demo modal, it uses a lot of memory for a small modal component.

**Comment by abhishekt98** [comment]
Facing this issue with significant delay. https://vimeo.com/700375666/a1591e8f01
Ref : https://github.com/bigbinary/neeto-wireframe-web/pull/1463

**Comment by karthiknmenon** [comment]
Should be fixed via https://github.com/bigbinary/neeto-ui/pull/1224.
