### ISSUE TITLE
Pane footer is still getting cut-off

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#832]
@praveen-murali-ind _a

This [commit](https://github.com/bigbinary/neeto-ui/pull/822/commits/048c30dc9bc99e687d9ec8cc247a51313ec0d89e) brings back the issue with Pane footer getting cut-off. Refer: https://github.com/bigbinary/neeto-ui/issues/824

Can you please revert this change or update the css? Thanks.

**Comment by praveen-murali-ind** [comment]
Closing this issue for now since the use case is specific and it can be easily fixed on the application side with minimal effort.

Ref - https://github.com/bigbinary/neeto-engage-web/pull/289#issuecomment-1036193887

We had added a fix for this in neetoUI, but we reverted as it was breaking the layout in some neeto applications because certain applications wrap Pane.Body with Formik and form. In such cases, the CSS height computation won’t work which will break the layout. 

One solution is to compute the height using JS which we can take as a separate issue if feasible.

//cc @karthiknmenon @amaldinesh7
